# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20180827_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khimagemodel',
            options={'verbose_name': 'Kunsthaus Image', 'verbose_name_plural': 'Kunsthaus Images'},
        ),
        migrations.AlterModelOptions(
            name='khimagemodeltranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Kunsthaus Image Translation'},
        ),
    ]
