# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0018_auto_20160802_1852'),
        ('myshop', '0003_auto_20180827_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='khimagemodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aldryn_people.Person', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='khimagemodel',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
    ]
