# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_auto_20180827_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khimagemodel',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='khimagemodel',
            name='battery_type',
        ),
        migrations.RemoveField(
            model_name='khimagemodel',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='khimagemodel',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='khimagemodel',
            name='ram_storage',
        ),
        migrations.RemoveField(
            model_name='khimagemodel',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='khimagemodel',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='khimagemodel',
            name='wifi_connectivity',
        ),
        migrations.AlterField(
            model_name='khimagemodel',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.Genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.Manufacturer', verbose_name='Manufacturer'),
        ),
    ]
