# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_auto_20180827_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khimagemodeltranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text="Full description used in the catalog's detail view of Smart Phones.", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.Manufacturer', verbose_name='Manufacturer'),
        ),
    ]
