# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_remove_scootermodel_ram_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scootermodel',
            name='wifi_connectivity',
        ),
    ]
