# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_remove_scootermodel_wifi_connectivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scootermodel',
            name='screen_size',
        ),
    ]
