# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_remove_scootermodel_screen_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='scootermodel',
            name='max_speed',
            field=models.DecimalField(decimal_places=0, default=0.0, help_text='Maxumum speed in km/h', max_digits=4, verbose_name='Maxumum speed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scootermodel',
            name='mileage',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Maxumum mileage per one battery charge in km', max_digits=4, verbose_name='Maxumum mileage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scootermodel',
            name='battery_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LG battery'), (2, 'Chinese battery')], verbose_name='Battery type'),
        ),
    ]
