# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_auto_20180830_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='scootermodel',
            name='power',
            field=models.DecimalField(decimal_places=0, default=250, help_text='Motor power in km', max_digits=4, verbose_name='Motor power'),
            preserve_default=False,
        ),
    ]
