# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_scootermodel_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scootermodel',
            name='height',
            field=models.DecimalField(decimal_places=0, help_text='Height in mm', max_digits=5, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='scootermodel',
            name='width',
            field=models.DecimalField(decimal_places=0, help_text='Width in mm', max_digits=5, verbose_name='Width'),
        ),
    ]
