# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_auto_20180830_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='scootermodel',
            name='battery_capacity',
            field=models.PositiveIntegerField(default=7800, help_text='Battery capacity in mAh', verbose_name='Capacity'),
            preserve_default=False,
        ),
    ]
