# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0018_auto_20180830_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scootermodel',
            name='battery_capacity',
        ),
    ]
