# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0020_auto_20180830_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scootermodel',
            name='weight',
            field=models.DecimalField(decimal_places=1, help_text='Weight in kg', max_digits=5, verbose_name='Weight'),
        ),
    ]
