# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0021_auto_20180830_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmartPhoneModel',
            new_name='SmartPhoneModel2',
        ),
        migrations.RenameModel(
            old_name='SmartPhoneModelTranslation',
            new_name='SmartPhoneModel2Translation',
        ),
        migrations.RemoveField(
            model_name='scootermodel',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='scootermodel',
            name='product_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='scootermodeltranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='scootermodeltranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='scootervariant',
            name='product',
        ),
        migrations.AlterModelTable(
            name='smartphonemodel2translation',
            table='myshop_smartphonemodel2_translation',
        ),
        migrations.DeleteModel(
            name='ScooterModel',
        ),
        migrations.DeleteModel(
            name='ScooterModelTranslation',
        ),
        migrations.DeleteModel(
            name='ScooterVariant',
        ),
    ]
