# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 13:16
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('myshop', '0023_auto_20180831_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='scootermodel',
            name='placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='contacts_contactsplaceholder', to='cms.Placeholder'),
        ),
    ]
