# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 13:25
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0024_scootermodel_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scootermodel',
            name='placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='product_details', to='cms.Placeholder'),
        ),
    ]
