# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0025_auto_20180831_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scootermodel',
            name='placeholder',
        ),
    ]
