# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0026_remove_scootermodel_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='scootermodel',
            name='depth',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Height in cm', max_digits=5, verbose_name='Depth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scootermodel',
            name='height',
            field=models.DecimalField(decimal_places=0, help_text='Height in cm', max_digits=5, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='scootermodel',
            name='width',
            field=models.DecimalField(decimal_places=0, help_text='Width in cm', max_digits=5, verbose_name='Width'),
        ),
    ]
