# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0027_auto_20180906_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='scootervariant',
            name='storage',
            field=models.PositiveIntegerField(default=0, help_text='Internal storage in MB', verbose_name='Internal Storage'),
            preserve_default=False,
        ),
    ]
