# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0029_remove_scootervariant_storage'),
        ('myshop', '0027_auto_20180917_1853'),
    ]

    operations = [
    ]
