# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0030_merge_20180919_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scootervariant',
            name='battery_capacity',
        ),
        migrations.AddField(
            model_name='scootervariant',
            name='color',
            field=models.CharField(choices=[(1, 'white'), (2, 'black')], default='white', max_length=255, verbose_name='Color'),
        ),
    ]
