# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0031_auto_20181004_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scootervariant',
            name='color',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black')], default='white', max_length=255, verbose_name='Color'),
        ),
    ]
